# Generated by Django 2.1.2 on 2018-10-11 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemSkuLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_sku', models.CharField(blank=True, max_length=255, null=True)),
                ('color', models.CharField(blank=True, max_length=255, null=True)),
                ('size', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('msrp', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('main_image', models.CharField(blank=True, max_length=255, null=True)),
                ('create_time', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'item_sku_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ItemUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_str', models.TextField(blank=True, null=True)),
                ('source_id', models.CharField(blank=True, max_length=255, null=True)),
                ('create_time', models.IntegerField(blank=True, null=True)),
                ('state', models.IntegerField(blank=True, null=True)),
                ('item_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'item_url',
                'managed': False,
            },
        ),
    ]
