# Generated by Django 2.1.2 on 2018-10-23 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fetch', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wishcrawlproduct',
            options={'managed': False},
        ),
    ]
