# Generated by Django 2.1.2 on 2018-10-21 20:16

from decimal import Decimal
from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('fetch', '0002_itemlog_joomstore'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=255)),
                ('platform_id', models.IntegerField(blank=True, null=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('client_id', models.CharField(blank=True, max_length=255, null=True)),
                ('client_secret', models.CharField(blank=True, max_length=255, null=True)),
                ('create_time', models.IntegerField(blank=True, null=True)),
                ('status', models.IntegerField()),
                ('access_token', models.TextField(blank=True, null=True)),
                ('refresh_token', models.TextField(blank=True, null=True)),
                ('already', models.IntegerField(blank=True, null=True)),
                ('sync_time', models.IntegerField(blank=True, null=True)),
                ('down_url', models.CharField(blank=True, max_length=255, null=True)),
                ('job_id', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'shop',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WishShop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_id', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=300, null=True)),
                ('url', models.CharField(blank=True, max_length=200, null=True)),
                ('createtime', models.IntegerField(blank=True, null=True)),
                ('modifytime', models.IntegerField(blank=True, null=True)),
                ('du_time', models.CharField(blank=True, max_length=20, null=True)),
                ('state', models.IntegerField(blank=True, null=True)),
                ('num', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'wish_shop',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WishCrawlProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_name', models.CharField(max_length=1024)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('msrp', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('sale_num', models.IntegerField(default=0)),
                ('default_img', models.CharField(blank=True, max_length=255, null=True)),
                ('list_img', models.TextField(blank=True, null=True)),
                ('introduce', models.TextField(blank=True, null=True)),
                ('score1', models.IntegerField(default=0)),
                ('score2', models.IntegerField(default=0)),
                ('score3', models.IntegerField(default=0)),
                ('score4', models.IntegerField(default=0)),
                ('score5', models.IntegerField(default=0)),
                ('average_score', models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=10)),
                ('cate', models.CharField(max_length=255, null=True)),
                ('source_id', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('create_time', models.IntegerField(null=True)),
                ('date_uploaded', models.DateTimeField(null=True)),
                ('tags', jsonfield.fields.JSONField(blank=True, null=True)),
                ('is_promoted', models.BooleanField(blank=True, null=True)),
                ('review_status', models.CharField(blank=True, max_length=12, null=True)),
                ('last_updated', models.DateTimeField(null=True)),
                ('parent_sku', models.CharField(max_length=50, null=True)),
                ('number_saves', models.IntegerField(null=True)),
                ('shop_id', models.IntegerField()),
            ],
            options={
                'db_table': 'wish_crawl_product',
            },
        ),
    ]
