# Generated by Django 2.1.2 on 2018-10-24 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fetch', '0002_auto_20181023_2229'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='joomstore',
            options={},
        ),
    ]
