# Generated by Django 2.1.2 on 2018-10-21 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fetch', '0003_shop_wishcrawlproduct_wishshop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishcrawlproduct',
            name='date_uploaded',
            field=models.DateField(null=True),
        ),
    ]
