# Generated by Django 2.1.2 on 2018-10-24 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fetch', '0003_auto_20181024_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joomstore',
            name='storeId',
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
