# Generated by Django 2.1.2 on 2018-10-21 20:42

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fetch', '0004_auto_20181021_2026'),
    ]

    operations = [
        migrations.CreateModel(
            name='WishVariantItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_sku', models.CharField(blank=True, max_length=255, null=True)),
                ('color', models.CharField(blank=True, max_length=255, null=True)),
                ('size', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.DecimalField(decimal_places=1, max_digits=10)),
                ('msrp', models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=10)),
                ('main_image', models.CharField(blank=True, max_length=255, null=True)),
                ('create_time', models.IntegerField(blank=True, null=True)),
                ('sku', models.CharField(blank=True, max_length=50, null=True)),
                ('variantId', models.CharField(blank=True, max_length=50, null=True)),
                ('shippingPrice', models.DecimalField(decimal_places=1, max_digits=10)),
                ('shipping_time', models.CharField(blank=True, max_length=40, null=True)),
                ('all_images', models.TextField(null=True)),
                ('enabled', models.BooleanField(null=True)),
            ],
            options={
                'db_table': 'wish_variant_item',
            },
        ),
    ]
